### ISSUE TITLE
Some row value strings make wordpress grazy

### ISSUE THREAD

**Issue by phylogram** [jupitern/table#6]
Before I describe this issue, let me tell you that: Thank You for this code, I really do not like to code html table output all the time and this repo is really great. 

So, the Issue is: I use this repo in a wordpress plugin and one of my columns had the id ``èdit_link```, which caused an wordpress 403 response "you can not edit links" (which I can).

Turns out changing the string into ```edit__link``` just works fine (with a double underscore).

So apparently your code somehow interferes with some wordpress callable / hook – I guess, I did not look deeper into it. In your repo it is caused by ```vendor/jupitern/table/src/Table/TableColumn.php``` line 172 - 182.

So I guess, you do not care for wordpress very much – I do neither, just working with it – however, maybe this will be an issue for someone later on.

So this is kind of FYI.

Thanks!

**Comment by phylogram** [comment]
I checked on it a little longer: It is not an wordpress issue. Every ```->value(($value)``` where ```$value``` is a string, where a function of the same name somewhere in the php script exists, will cause ```is_callable``` to return a truish value and therefore possibly break the script.

The only solution I can think about right now, is to check for every $value in the table definition is, if a function of the same name already exists. 

Maybe this would a solution: https://www.php.net/manual/de/reflectionfunctionabstract.isclosure.php

**Comment by jupitern** [comment]
Hi,
Can you pull master branch and test? the issue is that any string that has the name of a existing funcion is interpreted like a callable by php

echo is_callable('trim');
// true
