### ISSUE TITLE
Incorrectly generated attributes of the table

### ISSUE THREAD

**Issue by Elvinas** [jupitern/table#7]
Hello,

So just wanted to pull this library into my project, and noticed the problem.

If you look at the test1.php example and view the source code you will see that attributes are not correctly generated, for example:
->attr('table', 'cellspacing', '0') somehow in a markup becomes: table="cellspacing" and the attribute values are not printed anywhere.

**Comment by jupitern** [comment]
Hi,
I cannot reproduce that error. Can you please share the code? is the line ->attr('table', 'cellspacing', '0') placed bellow the table function and outside any column?
